//Automatically Returns Data Type of Tables Dynamically without hardcoding column names
(tbl as table, optional N_Rows as number)=>
let
    ColNames = Table.ColumnNames(tbl),
    N_Rows = (if N_Rows = null then Table.RowCount(tbl) else N_Rows),
    first_NRows = Table.ToColumns(Table.FirstN(tbl, N_Rows)),
    RemoveNulls = List.Transform(first_NRows, each List.RemoveNulls(_)),
    ConvertZerosToNulls = List.Transform(RemoveNulls, (r)=> List.Transform(r, each try (if Number.From(_) = 0 then null else _) otherwise _) ),
    RemoveNullZeros = List.Transform(ConvertZerosToNulls, each List.RemoveNulls(_)),
    GetFirstItem = List.Transform(RemoveNullZeros, each List.First(_)),
    TypeCastNumbers = List.Transform(GetFirstItem, each if _ = null then _ else if Text.StartsWith(_, "0") then _ else (try Number.From(_) otherwise _)),
    ValueType = List.Transform(TypeCastNumbers, each if _ = null then Any.Type else Value.Type(_)),
    DataTypes = List.Zip({ColNames, ValueType})
    in Table.TransformColumnTypes(tbl, DataTypes)
