(tbl as table, optional FIXED_COL_COUNT as number) =>
    let
        FIXED_COL_COUNT = if FIXED_COL_COUNT = null then 30 else FIXED_COL_COUNT,
        num_of_cols = if Table.ColumnCount(tbl) > FIXED_COL_COUNT then FIXED_COL_COUNT else Table.ColumnCount(tbl),

        select_columns = 
        let source = List.Generate(
                ()=> 1,
                each _ <= num_of_cols,
                each _ + 1,
                each "Column" & Text.From(_)
            )
        in
            source

    in Table.SelectColumns(tbl,  select_columns)
