// return table with blank columns removed
(tbl as table) =>

let
    col_names = Table.ColumnNames(tbl), // get column names
    tbl_no_erors =  Table.ReplaceErrorValues(tbl, List.Transform(col_names, each {_, null})), //remove errors

// fx to check if column has null or empty values
   Is_Null_Column_Values = (tbl as table, col_name)  => 

        let
            empty_values_list = {null, ""},
            col_values = List.Transform(Table.Column(tbl, col_name), each try Text.Trim(_) otherwise _), //remove spaces
            is_null_all = List.MatchesAll(col_values , each  List.ContainsAny(empty_values_list, {_}) )
        in
            is_null_all,

    // fx to get col names of empty or null columns
    non_empty_columns =  (tbl as table)=>
        let col_states =
                List.Generate(
                    ()=> [col = col_names{count}, count = 0, is_null = Is_Null_Column_Values(tbl, col)],
                    each [count] < List.Count(col_names),
                    each [col = col_names{count}, count = [count] + 1, is_null = Is_Null_Column_Values(tbl, col)],
                    each [ col = if not [is_null] then [col] else null ][col]
                )
        in  List.Select(col_states, each _ <> null )

in 
   Table.SelectColumns(tbl, non_empty_columns(tbl_no_erors))
