// return a table with empty rows removed
(tbl as table)=>
let
    CountNonNullColumns = Table.AddColumn(tbl, "Custom", each List.NonNullCount(Record.FieldValues(_))), //Check the count of non-null columns
    RemoveNullRows = Table.SelectRows(CountNonNullColumns, each ([Custom] <> 0)) //Remove records with zero non-null count
in
    Table.RemoveColumns(RemoveNullRows,{"Custom"})
