// return table with blank columns removed
(tbl as table)=>

let 
//Function to get all the empty columns
fxGetEmptyColumns = 
            (tbl as table)=>

            let ColNames = Table.ColumnNames(tbl),

            //============Function to check if a column is empty
            fxIsColumnEmpty = 
                    (tbl as table, colName as text) =>
                    let
                        RemovedOtherColumns = Table.SelectColumns(tbl,{colName}),
                        change_col_data_type = Table.TransformColumnTypes(tbl, {colName, type text}),
                        TrimmedText = Table.TransformColumns(change_col_data_type,{{colName, Text.Trim}}),
                        ReplacedValue = Table.ReplaceValue(TrimmedText,"",null,Replacer.ReplaceValue,{colName})
                    in
                        List.MatchesAll(Table.Column(ReplacedValue, colName), each _ = null),
            //===========================================================================

            emptyCols = List.Accumulate(
                ColNames,
                {}, (state, curr)=> if fxIsColumnEmpty(tbl, curr) then state & {curr} else state & {}
            )

            in emptyCols
//=====================================================

in
Table.RemoveColumns(tbl, fxGetEmptyColumns(tbl))
