// return a table with empty rows removed
(tbl as table) as table =>

let 
    IsEmptyRecord = (record_ as record) =>
        (
        let
            record_to_list = Record.ToList(record_),
            converted_to_Table = Table.FromList(record_to_list, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
            TrimmedText = Table.TransformColumns(Table.TransformColumnTypes(converted_to_Table, {{"Column1", type text}}), 
                                {{"Column1", Text.Trim, type text}}),
            ReplacedValue = Table.ReplaceValue(TrimmedText,"",null,Replacer.ReplaceValue,{"Column1"})[Column1]
        in
            List.MatchesAll(ReplacedValue, each _ = null)
            )

in
    Table.SelectRows(tbl, each not IsEmptyRecord(_))
