//Return a table after removing empty columns
(tbl as table)=>
let
    replace_empties = Table.ReplaceValue(tbl," ", null, Replacer.ReplaceValue, Table.ColumnNames(tbl)),
    GetTableProfile = Table.Profile(replace_empties),
    DrillDownToColumnNullCount = Table.SelectColumns(GetTableProfile,{"Column", "NullCount"}),
    row_count = Table.RowCount(tbl),
    GetAllNullCount = Table.SelectRows(DrillDownToColumnNullCount, each [NullCount] = row_count),
    ToRemoveColList = GetAllNullCount[Column]
in
    Table.RemoveColumns(tbl, ToRemoveColList)
