//Return a table after removing empty columns
(tbl as table)=>
let
    GetTableProfile = Table.Profile(tbl),
    DrillDownToColumnNullCount = Table.SelectColumns(GetTableProfile,{"Column", "NullCount"}),
    row_count = Table.RowCount(tbl),
    GetAllNullCount = Table.SelectRows(DrillDownToColumnNullCount, each [NullCount] = row_count),
    ToRemoveColList = GetAllNullCount[Column]
in
    Table.RemoveColumns(tbl, ToRemoveColList)
