//Automatically determines data type of columns
(tbl as table) as table =>

let 
//=============Return List of Column Names and Data Types============================
fxDataType =
    (tbl as table) =>

    let
        ROW_LIMIT = 100,
        FirstRows = if Table.RowCount(tbl) > ROW_LIMIT then Table.FirstN(tbl, ROW_LIMIT) else tbl, //Select first rows based on ROW_LIMIT
        ColNames = Table.ColumnNames(tbl), //Get columns names

        //-----function to determine data type using a value at index----
        data_type = (colName as text)=>
            let
                RemovedOtherColumns = Table.SelectColumns(FirstRows, colName),
                // change_dataType_to_text = Table.TransformColumnTypes(RemovedOtherColumns, {colName, type text}), //before trimming
                // TrimmedText = Table.TransformColumns(change_dataType_to_text,{{colName, Text.Trim, type text}}), //Remove leading and lagging spaces
                ReplacedValue = Table.ReplaceValue(RemovedOtherColumns,"",null,Replacer.ReplaceValue,{colName}), //replace blanks with null
                Col_to_list = Table.Column(ReplacedValue, colName), //convert table column to list
                RemoveNulls = List.RemoveNulls(Col_to_list),
                First_Item = if List.NonNullCount(RemoveNulls) = 0 then "xxx" else List.First(RemoveNulls) //after removing null, if list returns blank
            in 
                try Value.Type(First_Item) otherwise (type text),
        //-----------------------------------------

        col_and_data_types = 
                List.Generate(
                    ()=> [index = 0, colName = ColNames{index}, outputCol = {colName, data_type(colName)}], //outputCol = a list of lists containing column name and colum data type for Table.TransformColumnTypes function
                    each [index] < List.Count(ColNames),
                    each [index = [index] + 1, colName = ColNames{index}, outputCol = {colName, data_type(colName)}],
                    each [outputCol]
                )

    in
        col_and_data_types
//=======================================================================================

//Final Output
in
    Table.TransformColumnTypes(tbl, fxDataType(tbl))
